services:
  - type: web
    name: incident-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
